use_frameworks!

target 'gqbaoMailSender_Example' do
  pod 'gqbaoMailSender', :path => '../'

  target 'gqbaoMailSender_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
